Zion@huang
1instinct/dna-frontend pull request #4
Opened 2021-05-21 03:09 UTC by zionhjs

Added MenuBar component and Footer component and its ReadMe

2021-05-22 00:49 UTC, zionhjs commented
new PR for fix the footer

2021-05-27 23:19 UTC, aaronsmulktis commented
hey hey I like what Vercel pointed out:

- We should only use one package manager, lets use `yarn` instead of `npm`, so on this branch I would try trashing the package-lock.json file and then run `yarn install` to regenerate.
- We should destructure the props on the first line of the Footer:
`const Footer = ({ links, showLegal, showContact, showSocial, styles }) = {...`
We should explicitly add the types in that first line too, defined inline or in a type declaration just above...
and then remove the desctructure line below inside the component

I think after those changes we're ready to merge!

2021-05-27 23:24 UTC, aaronsmulktis commented
We need to start being more type-strict for sure, this app is going to get big

2021-06-02 01:54 UTC, gitstud requested changes

2021-06-02 01:54 UTC, gitstud commented on components/MainMenu/BurgerIcon.tsx
> +  let buttonStyle = {
It looks like we have some let declarations here that are never reassigned, it would be better to use const for these variables

2021-06-04 00:22 UTC, aaronsmulktis commented
@zionhjs to fix these merge conflicts and make it a clean merge, follow these steps:
```
git checkout main
git pull origin main
git checkout zion@huang
git merge main

```
Fix all the merge conflicts locally
Add your changes, commit, and push!

…then the PR on github.com should show a clean merge, with no conflicts :slightly_smiling_face:

2021-06-04 17:38 UTC, zionhjs commented
PR to main

2021-06-04 17:39 UTC, merged